# fly.toml app configuration file generated for hilopalace on 2023-06-15T10:30:06-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hilopalace"
primary_region = "lax"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[deploy]
  strategy = "bluegreen"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
